apiVersion: v1
kind: Pod

metadata:
  name: config-ref-demo 
spec:
  containers: 
    - name: nginx
      image: nginx
      env:
        - name: course 
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: course

        - name: trainer 
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: trainer

        - name: duration 
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: duration