apiVersion: v1
kind: Pod

metadata:
  name: config-ref-demo 
spec:
  containers: 
    - name: nginx
      image: nginx
      env:
        - name: course
          valueFrom:
          congigMaKeypRef:
            name: nginx-config
            value: course
        